# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client/CMakeFiles /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client/Tasks/CMakeFiles/progress.marks
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(MAKE) -f CMakeFiles/Makefile2 Tasks/all
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(MAKE) -f CMakeFiles/Makefile2 Tasks/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(MAKE) -f CMakeFiles/Makefile2 Tasks/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(MAKE) -f CMakeFiles/Makefile2 Tasks/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
Tasks/CMakeFiles/t_st.dir/rule:
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(MAKE) -f CMakeFiles/Makefile2 Tasks/CMakeFiles/t_st.dir/rule
.PHONY : Tasks/CMakeFiles/t_st.dir/rule

# Convenience name for target.
t_st: Tasks/CMakeFiles/t_st.dir/rule

.PHONY : t_st

# fast build rule for target.
t_st/fast:
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(MAKE) -f Tasks/CMakeFiles/t_st.dir/build.make Tasks/CMakeFiles/t_st.dir/build
.PHONY : t_st/fast

# Convenience name for target.
Tasks/CMakeFiles/moveForward.dir/rule:
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(MAKE) -f CMakeFiles/Makefile2 Tasks/CMakeFiles/moveForward.dir/rule
.PHONY : Tasks/CMakeFiles/moveForward.dir/rule

# Convenience name for target.
moveForward: Tasks/CMakeFiles/moveForward.dir/rule

.PHONY : moveForward

# fast build rule for target.
moveForward/fast:
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(MAKE) -f Tasks/CMakeFiles/moveForward.dir/build.make Tasks/CMakeFiles/moveForward.dir/build
.PHONY : moveForward/fast

# Convenience name for target.
Tasks/CMakeFiles/task1.1.dir/rule:
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(MAKE) -f CMakeFiles/Makefile2 Tasks/CMakeFiles/task1.1.dir/rule
.PHONY : Tasks/CMakeFiles/task1.1.dir/rule

# Convenience name for target.
task1.1: Tasks/CMakeFiles/task1.1.dir/rule

.PHONY : task1.1

# fast build rule for target.
task1.1/fast:
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(MAKE) -f Tasks/CMakeFiles/task1.1.dir/build.make Tasks/CMakeFiles/task1.1.dir/build
.PHONY : task1.1/fast

# Convenience name for target.
Tasks/CMakeFiles/task1.dir/rule:
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(MAKE) -f CMakeFiles/Makefile2 Tasks/CMakeFiles/task1.dir/rule
.PHONY : Tasks/CMakeFiles/task1.dir/rule

# Convenience name for target.
task1: Tasks/CMakeFiles/task1.dir/rule

.PHONY : task1

# fast build rule for target.
task1/fast:
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(MAKE) -f Tasks/CMakeFiles/task1.dir/build.make Tasks/CMakeFiles/task1.dir/build
.PHONY : task1/fast

# Convenience name for target.
Tasks/CMakeFiles/task1.2.dir/rule:
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(MAKE) -f CMakeFiles/Makefile2 Tasks/CMakeFiles/task1.2.dir/rule
.PHONY : Tasks/CMakeFiles/task1.2.dir/rule

# Convenience name for target.
task1.2: Tasks/CMakeFiles/task1.2.dir/rule

.PHONY : task1.2

# fast build rule for target.
task1.2/fast:
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(MAKE) -f Tasks/CMakeFiles/task1.2.dir/build.make Tasks/CMakeFiles/task1.2.dir/build
.PHONY : task1.2/fast

ScratchPad.o: ScratchPad.c.o

.PHONY : ScratchPad.o

# target to build an object file
ScratchPad.c.o:
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(MAKE) -f Tasks/CMakeFiles/t_st.dir/build.make Tasks/CMakeFiles/t_st.dir/ScratchPad.c.o
.PHONY : ScratchPad.c.o

ScratchPad.i: ScratchPad.c.i

.PHONY : ScratchPad.i

# target to preprocess a source file
ScratchPad.c.i:
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(MAKE) -f Tasks/CMakeFiles/t_st.dir/build.make Tasks/CMakeFiles/t_st.dir/ScratchPad.c.i
.PHONY : ScratchPad.c.i

ScratchPad.s: ScratchPad.c.s

.PHONY : ScratchPad.s

# target to generate assembly for a file
ScratchPad.c.s:
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(MAKE) -f Tasks/CMakeFiles/t_st.dir/build.make Tasks/CMakeFiles/t_st.dir/ScratchPad.c.s
.PHONY : ScratchPad.c.s

moveForward.o: moveForward.c.o

.PHONY : moveForward.o

# target to build an object file
moveForward.c.o:
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(MAKE) -f Tasks/CMakeFiles/moveForward.dir/build.make Tasks/CMakeFiles/moveForward.dir/moveForward.c.o
.PHONY : moveForward.c.o

moveForward.i: moveForward.c.i

.PHONY : moveForward.i

# target to preprocess a source file
moveForward.c.i:
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(MAKE) -f Tasks/CMakeFiles/moveForward.dir/build.make Tasks/CMakeFiles/moveForward.dir/moveForward.c.i
.PHONY : moveForward.c.i

moveForward.s: moveForward.c.s

.PHONY : moveForward.s

# target to generate assembly for a file
moveForward.c.s:
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(MAKE) -f Tasks/CMakeFiles/moveForward.dir/build.make Tasks/CMakeFiles/moveForward.dir/moveForward.c.s
.PHONY : moveForward.c.s

task1.1.o: task1.1.c.o

.PHONY : task1.1.o

# target to build an object file
task1.1.c.o:
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(MAKE) -f Tasks/CMakeFiles/task1.1.dir/build.make Tasks/CMakeFiles/task1.1.dir/task1.1.c.o
.PHONY : task1.1.c.o

task1.1.i: task1.1.c.i

.PHONY : task1.1.i

# target to preprocess a source file
task1.1.c.i:
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(MAKE) -f Tasks/CMakeFiles/task1.1.dir/build.make Tasks/CMakeFiles/task1.1.dir/task1.1.c.i
.PHONY : task1.1.c.i

task1.1.s: task1.1.c.s

.PHONY : task1.1.s

# target to generate assembly for a file
task1.1.c.s:
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(MAKE) -f Tasks/CMakeFiles/task1.1.dir/build.make Tasks/CMakeFiles/task1.1.dir/task1.1.c.s
.PHONY : task1.1.c.s

task1.2.o: task1.2.c.o

.PHONY : task1.2.o

# target to build an object file
task1.2.c.o:
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(MAKE) -f Tasks/CMakeFiles/task1.2.dir/build.make Tasks/CMakeFiles/task1.2.dir/task1.2.c.o
.PHONY : task1.2.c.o

task1.2.i: task1.2.c.i

.PHONY : task1.2.i

# target to preprocess a source file
task1.2.c.i:
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(MAKE) -f Tasks/CMakeFiles/task1.2.dir/build.make Tasks/CMakeFiles/task1.2.dir/task1.2.c.i
.PHONY : task1.2.c.i

task1.2.s: task1.2.c.s

.PHONY : task1.2.s

# target to generate assembly for a file
task1.2.c.s:
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(MAKE) -f Tasks/CMakeFiles/task1.2.dir/build.make Tasks/CMakeFiles/task1.2.dir/task1.2.c.s
.PHONY : task1.2.c.s

task1.o: task1.c.o

.PHONY : task1.o

# target to build an object file
task1.c.o:
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(MAKE) -f Tasks/CMakeFiles/task1.dir/build.make Tasks/CMakeFiles/task1.dir/task1.c.o
.PHONY : task1.c.o

task1.i: task1.c.i

.PHONY : task1.i

# target to preprocess a source file
task1.c.i:
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(MAKE) -f Tasks/CMakeFiles/task1.dir/build.make Tasks/CMakeFiles/task1.dir/task1.c.i
.PHONY : task1.c.i

task1.s: task1.c.s

.PHONY : task1.s

# target to generate assembly for a file
task1.c.s:
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(MAKE) -f Tasks/CMakeFiles/task1.dir/build.make Tasks/CMakeFiles/task1.dir/task1.c.s
.PHONY : task1.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... t_st"
	@echo "... moveForward"
	@echo "... task1.1"
	@echo "... rebuild_cache"
	@echo "... task1"
	@echo "... task1.2"
	@echo "... ScratchPad.o"
	@echo "... ScratchPad.i"
	@echo "... ScratchPad.s"
	@echo "... moveForward.o"
	@echo "... moveForward.i"
	@echo "... moveForward.s"
	@echo "... task1.1.o"
	@echo "... task1.1.i"
	@echo "... task1.1.s"
	@echo "... task1.2.o"
	@echo "... task1.2.i"
	@echo "... task1.2.s"
	@echo "... task1.o"
	@echo "... task1.i"
	@echo "... task1.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /cygdrive/c/Users/User/Downloads/AltSimulator_Release_170110/Client && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

